/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tesoreria;

import Jva_centroCosto.MaestroProveedor;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus-PC
 */
public class plantilla_Incripcion_Maestro_Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form Maestro_Proveedores
     */
    public plantilla_Incripcion_Maestro_Proveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NIT_mestroProveedor = new javax.swing.JTextField();
        Nombre_mestroProveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Direccion_mestroProveedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Telefono_mestroProveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Ciudad_mestroProveedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Tipo_mestroProveedor = new javax.swing.JTextField();
        Guardar_maestroProveedor = new javax.swing.JButton();
        Cancela_mestroProveedor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setText("Inscripcion de Maestro Proveedores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText("NIT");

        jLabel3.setText("Nombre");

        NIT_mestroProveedor.setText("ingrese NIT de empresa");
        NIT_mestroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIT_mestroProveedorActionPerformed(evt);
            }
        });

        Nombre_mestroProveedor.setText("ingrese nombre de la empresa");
        Nombre_mestroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_mestroProveedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Direccion");

        Direccion_mestroProveedor.setText("ingrese direccion");
        Direccion_mestroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Direccion_mestroProveedorActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefono");

        Telefono_mestroProveedor.setText("ingrese telefono");
        Telefono_mestroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Telefono_mestroProveedorActionPerformed(evt);
            }
        });

        jLabel6.setText("Ciudad");

        Ciudad_mestroProveedor.setText("ingrese ciuadad");
        Ciudad_mestroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ciudad_mestroProveedorActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo");

        Tipo_mestroProveedor.setText("ingrese tipo");
        Tipo_mestroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tipo_mestroProveedorActionPerformed(evt);
            }
        });

        Guardar_maestroProveedor.setText("Guardar");
        Guardar_maestroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_maestroProveedorActionPerformed(evt);
            }
        });

        Cancela_mestroProveedor.setText("Cancelar");
        Cancela_mestroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancela_mestroProveedorActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Nombre_mestroProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(NIT_mestroProveedor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Direccion_mestroProveedor)
                                    .addComponent(Telefono_mestroProveedor)
                                    .addComponent(Ciudad_mestroProveedor)
                                    .addComponent(Tipo_mestroProveedor))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Guardar_maestroProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancela_mestroProveedor)
                        .addGap(56, 56, 56))))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NIT_mestroProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nombre_mestroProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Direccion_mestroProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Telefono_mestroProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Ciudad_mestroProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Tipo_mestroProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar_maestroProveedor)
                    .addComponent(Cancela_mestroProveedor))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int Nit = 01;
    long Telefono = 1;
    String nombre = "", direccion = "", ciudad = "", tipo = "";
    //MaestroProveedor teacher = new MaestroProveedor(Nit, nombre, direccion, ciudad, tipo, Telefono);
    Scanner sc = new Scanner(System.in);

    /*    int a= Integer.parseInt(JOptionPane.showInputDialog("Escribir el nit empresa"));
        String b = JOptionPane.showInputDialog("Escribir el nombre");
        String c = JOptionPane.showInputDialog("ingrese la direccion");
        String d = JOptionPane.showInputDialog("agrege una ciudad");        
        String e = JOptionPane.showInputDialog("describa el tipo");
        int f = Integer.parseInt(JOptionPane.showInputDialog("entregue el telefono"));*/
    private void NIT_mestroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIT_mestroProveedorActionPerformed

        //  Scanner sc = new Scanner(System.in);
        // int a = sc.nextInt(); //String a = sc.next();
        Nit = sc.nextInt();    // TODO add your handling code here:
        System.out.println(Nit);
        //teacher.setNit(Nit);
    }//GEN-LAST:event_NIT_mestroProveedorActionPerformed

    private void Nombre_mestroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_mestroProveedorActionPerformed
        // TODO add your handling code here:

        // Scanner sc = new Scanner(System.in); String a = sc.next();
        nombre = sc.next();
        System.out.println(nombre);
        //teacher.setNombre(nombre);
    }//GEN-LAST:event_Nombre_mestroProveedorActionPerformed

    private void Direccion_mestroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Direccion_mestroProveedorActionPerformed
        // TODO add your handling code here:

        //Scanner sc = new Scanner(System.in); String a = sc.next();
        direccion = sc.next();
        System.out.println(direccion);
        //teacher.setDireccion(direccion);
    }//GEN-LAST:event_Direccion_mestroProveedorActionPerformed

    private void Telefono_mestroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Telefono_mestroProveedorActionPerformed
        // TODO add your handling code here:

        // Scanner sc = new Scanner(System.in);long a = sc.nextLong();
        Telefono = sc.nextLong();
        System.out.println(Telefono);
        //teacher.setTelefono(Telefono);
    }//GEN-LAST:event_Telefono_mestroProveedorActionPerformed

    private void Ciudad_mestroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ciudad_mestroProveedorActionPerformed
        // TODO add your handling code here:

        // Scanner sc = new Scanner(System.in); String a = sc.next();
        ciudad = sc.next();
        System.out.println(ciudad);
        //teacher.setCiudad(ciudad);
    }//GEN-LAST:event_Ciudad_mestroProveedorActionPerformed

    private void Tipo_mestroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tipo_mestroProveedorActionPerformed
        // TODO add your handling code here:

        //  Scanner sc = new Scanner(System.in);  String a = sc.next();
        tipo = sc.next();
        System.out.println(tipo);
        //teacher.setTipo(tipo);
    }//GEN-LAST:event_Tipo_mestroProveedorActionPerformed
    int cont = 0;

    /*   int Nit=01;
    long Telefono=1;
    String nombre="", direccion="", ciudad="", tipo="";*/
    private void Guardar_maestroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_maestroProveedorActionPerformed
        // TODO add your handling code here:
        plantilla_Incripcion_Maestro_Proveedores admin = new plantilla_Incripcion_Maestro_Proveedores();

        //String numCadena= Integer.toString(numEntero);
        String nit = String.valueOf(Nit);
        nit = this.NIT_mestroProveedor.getText();
        String telefono = String.valueOf(Telefono);
        telefono = this.Telefono_mestroProveedor.getText();
        nombre = this.Nombre_mestroProveedor.getText();
        direccion = this.Direccion_mestroProveedor.getText();
        ciudad = this.Ciudad_mestroProveedor.getText();
        tipo = this.Tipo_mestroProveedor.getText();
        admin.crear(nit, telefono, nombre, direccion, ciudad, tipo);
    }//GEN-LAST:event_Guardar_maestroProveedorActionPerformed
    public void crear(String nit, String telefono, String nombre, String direccion, String ciudad, String tipo) {
        cont++;
        int nitt = Integer.parseInt(nit);
        Nit = nitt;
        int celular = Integer.parseInt(telefono);
        Telefono = celular;

        MaestroProveedor teacher = new MaestroProveedor(Nit, nombre, direccion, ciudad, tipo, Telefono);
        List<MaestroProveedor> integrantes = new ArrayList<MaestroProveedor>();
        integrantes.add(teacher);

        String b = "#]identificacion)nombre\n";
        int cont = 1;
        for (MaestroProveedor proveedor : integrantes) {
            System.out.println(cont + ", " + proveedor.getNit() + ", " + proveedor.getNombre()
                    + proveedor.getDireccion() + proveedor.getCiudad() + proveedor.getTipo() + proveedor.getTelefono());
            b += "\n" + cont + "] " + proveedor.getNit() + ") " + proveedor.getNombre() + ") "
                    + proveedor.getDireccion() + ") " + proveedor.getCiudad() + ") " + proveedor.getTipo()
                    + ") " + proveedor.getTelefono();
            cont++;
        }
        JOptionPane.showMessageDialog(null, "\"lo almacenado es:\n " + b);

    }
    private void Cancela_mestroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancela_mestroProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancela_mestroProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plantilla_Incripcion_Maestro_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plantilla_Incripcion_Maestro_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plantilla_Incripcion_Maestro_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plantilla_Incripcion_Maestro_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new plantilla_Incripcion_Maestro_Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancela_mestroProveedor;
    private javax.swing.JTextField Ciudad_mestroProveedor;
    private javax.swing.JTextField Direccion_mestroProveedor;
    private javax.swing.JButton Guardar_maestroProveedor;
    private javax.swing.JTextField NIT_mestroProveedor;
    private javax.swing.JTextField Nombre_mestroProveedor;
    private javax.swing.JTextField Telefono_mestroProveedor;
    private javax.swing.JTextField Tipo_mestroProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
